Repository ISIS3510-202510-T14/Mobile, pull requests merged in 2025-04, with the labels that each got.

#56 phamton users checking on client side
  lib/data/services/backend_api.dart
  lib/presentation/screens/create_account_screen.dart
  lib/presentation/screens/login_screen.dart
Labels: bug

#57 bet history view
  lib/data/models/bet_model.dart
  lib/data/models/bet_with_match.dart
  lib/data/repositories/bet_repository.dart
  lib/data/repositories/match_repository.dart
  lib/data/services/database_helper.dart
  lib/presentation/screens/home_screen.dart
  lib/presentation/screens/place_bet_view.dart
  lib/presentation/screens/user_bets_screen.dart
  lib/presentation/viewmodels/user_bets_view_model.dart
Labels: enhancement

#59 Feature/aesthetic improvement #58
  lib/presentation/screens/place_bet_view.dart
  lib/presentation/screens/recommended_bet_screen.dart
  lib/presentation/screens/sign_up_screen.dart
  lib/presentation/screens/user_bets_screen.dart
  lib/presentation/widgets/finished_match_card.dart
  lib/presentation/widgets/live_match_card.dart
  lib/presentation/widgets/match_card.dart
Labels: bug, enhancement

#61 Feature/ec place bet #42
  devtools_options.yaml
  lib/data/models/bet_model.dart
  lib/data/repositories/bet_repository.dart
  lib/data/services/backend_api.dart
  lib/data/services/database_helper.dart
  lib/data/services/draft_sync_service.dart
  lib/main.dart
  lib/presentation/screens/place_bet_view.dart
  lib/presentation/viewmodels/bet_viewmodel.dart
  lib/presentation/viewmodels/matches_view_model.dart
  lib/presentation/viewmodels/user_bets_view_model.dart
  lib/presentation/widgets/live_match_card.dart
  lib/presentation/widgets/match_card.dart
  lib/presentation/widgets/sync_status_listener.dart
Labels: enhancement, Sprint 3

#64 multi threading for sync bets
  lib/data/services/background_sync_service.dart
  lib/data/services/draft_sync_service.dart
  lib/data/services/isolate_manager.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, Sprint 3

#60 [ #39 ] User Authentication leverages Local Storage for Email and AutoLogin
  lib/main.dart
  lib/presentation/screens/login_screen.dart
  lib/presentation/screens/matches_view.dart
  lib/presentation/viewmodels/auth_wrapper_viewmodel.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement, Sprint 3

#65 error logging in local storage
  check_last_conn_errors.sql
  lib/data/repositories/error_log_repository.dart
  lib/data/services/backend_api.dart
  lib/data/services/connectivity_service.dart
  lib/data/services/database_helper.dart
  lib/data/services/isolate_manager.dart
  lib/presentation/viewmodels/bet_viewmodel.dart
  lib/presentation/viewmodels/matches_view_model.dart
  lib/presentation/viewmodels/recommended_bet_viewmodel.dart
  lib/presentation/viewmodels/user_bets_view_model.dart
Labels: enhancement

#69 [ #51 ] Login Screen Eventual Connectivity Strategy
  lib/presentation/screens/login_screen.dart
Labels: enhancement, Sprint 3

#68 [ #52 ] Implement EC and local storage for recommended bets
  lib/data/services/database_helper.dart
  lib/presentation/screens/recommended_bet_screen.dart
  lib/presentation/viewmodels/recommended_bet_viewmodel.dart
Labels: enhancement, Sprint 3

#71 Fix/place bet local storage bugs #66
  lib/data/repositories/bet_repository.dart
  lib/data/services/database_helper.dart
  lib/presentation/viewmodels/user_bets_view_model.dart
Labels: bug

#70 [ #63 ] Implement BQ of Average Response Time from Endpoint
  .gitignore
  lib/data/services/backend_api.dart
  lib/data/services/isolate_manager.dart
  lib/data/services/metrics_db_helper.dart
  lib/data/services/metrics_management.dart
  lib/presentation/viewmodels/bet_viewmodel.dart
  lib/presentation/viewmodels/matches_view_model.dart
  lib/presentation/viewmodels/recommended_bet_viewmodel.dart
  lib/presentation/viewmodels/user_bets_view_model.dart
Labels: enhancement, Sprint 3
